### ISSUE TITLE
Code cannot be minified

### ISSUE THREAD

**Issue by pineapplemachine** [StephanHoyer/classies#6]
I noticed this when building a newer version of the [microjs](https://github.com/microjs/microjs.com) website. Minification fails with an error:  `Invalid assignment (line: 1, col: 38)` (via https://jscompress.com/)

Unfortunately, failed minification prevents your submission from being included on the site. Please fix this error so that classies can be included with the next build!

**Comment by StephanHoyer** [comment]
If you enable ES2019, it works perfectly fine.

I don't want to compile this in advance. Is there any possibility that this can be solved otherwise?
